# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Publish Docker image

on:
  push

jobs:
  push_to_registry_pc_image:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        platform: [pc, jetson]
        zed_version: [3.5]

    steps:
      - name: Set up QEMU
        if: ${{ matrix.platform == 'jetson' }}
        uses: docker/setup-qemu-action@v1
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Check out the repo
        uses: actions/checkout@v2
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      # - name: Extract metadata (tags, labels) for Docker
      #   id: meta
      #   uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
      #   with:
      #     images: codustry/ros
      
      - name: Build and push Docker image for 
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: circleoncircles/ros-zed:${{ matrix.platform }}-${{ matrix.zed_version }}
          file: Dockerfile.${{ matrix.platform }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: ZED_SDK_VERSION=${{ matrix.zed_version }}
      
